Use mlx5 vf as PF1 proxy
ironcore-dev/dpservice pull request #614
Opened 2024-10-01 16:24 UTC by PlagueCZ

Given TAP device's limitations, we implemented the PF1-proxy using a VF bound to MLX5 driver (as opposed to VFIO). This VF is created on PF1 to make it easier to set up.

This also enables offloading of the proxy path. For normal operation this is easy, for OSC vith virtual services, there is a little bit more work, but nothing major.

I tried to reorder and squash commits into blocks of work, so this PR should be nicely readable by going through it commit-by-commit.

I had to change the prepare script, but it should be backwards-compatible. There is one reordering (setting switchdev before setting the number of VFs) that is needed for multiport mode. OSC is also now provisioning the HW differently, so I only tested the prepare script's HW setup by hand locally. 

Connected to #606

2024-10-02 10:28 UTC, PlagueCZ commented on include/rte_flow/dp_rte_flow_helpers.h
> +static const struct rte_flow_item_ipv6 dp_flow_item_ipv6_src_dst_mask = {
Well they all contain proto (dp_flow_item_ipv6_mask, dp_flow_item_ipv6_src_mask, dp_flow_item_ipv6_dst_mask), that's why I kept it and the one without proto is dp_flow_item_ipv6_dst_only_mask

But we can rename all of these if you like.

2024-10-02 10:29 UTC, PlagueCZ commented on include/dp_port.h
> +	DP_PORT_ASYNC_TEMPLATE_PF1_FROM_PROXY,
The idea was that "pf1 to proxy" and "proxy to pf1" seem similar, whereas "from" is directly telling me the direction is reversed. But if you prefer I can simply rename.

Though the some more functions would need renaming, like `dp_create_pf_async_from_proxy_templates`, `dp_create_pf_async_to_proxy_templates` etc.

2024-10-02 10:31 UTC, PlagueCZ commented on src/rte_flow/dp_rte_async_flow_isolation.c
> +		// cannot end on error, need to commit partial success
We would no like to keep going as this impacts performance and we found that Ceph storage degrades rapidly making the stack unusable, so failing is preferred.

Setting the link down would then "disable" the possibility of updating the switch, which is also not something we can allow.

2024-10-02 10:32 UTC, PlagueCZ commented
As for the graph schema, I thought about it, but given that virtual services are also not there because they are in an `ifdef`, I dod not do it.

But if it's wanted I could create two copies of the shema and create a virtual-services-specific one and pf1-proxy-specific one.

2024-10-03 12:05 UTC, PlagueCZ commented on src/rte_flow/dp_rte_async_flow_isolation.c
> +		// cannot end on error, need to commit partial success
Updated comments to be more clear

2024-10-03 12:05 UTC, PlagueCZ commented on src/dp_port.c
> +	if (dp_conf_is_pf1_proxy_enabled() && port == dp_get_pf0()) {
Good point, added a comment

2024-10-08 08:03 UTC, byteocean approved these changes
LGTM.

2024-10-16 11:22 UTC, guvenc commented
@PlagueCZ 
I am still going through the changes but one thing which popped into my mind is that clang build which is run anyways and produces throw away binary during the CI/CD can include the compiler flag of pf1 proxy so that this newly introduced code path gets compiled at least once during CI/CD.

2024-10-16 11:29 UTC, PlagueCZ commented
We should really run a tester in a job in OSC, but unfortunately that is still not being done.
We should then add another compilation run though, because I already had clang catch a warning about unused variable, which was unused due to pf1-proxy *not* being there

2024-10-17 12:19 UTC, guvenc requested changes
@PlagueCZ 
I think this PR is in good shape. Thanks also for providing the updated dataplane graph schema.
- Let's add a (temporary) compilation step in Dockerfile where this newly introduced feature is enabled, as discussed.

- And also the clarification whether the RoCE needs to be disabled on firmware level to get a good performance when mpesw is enabled. If so, documenting it in the docs with a sentence or so.

- And also please rebase to main. 

Apart from these things, in pretty good shape. Thanks !

2024-10-17 17:09 UTC, guvenc approved these changes

2024-10-17 17:26 UTC, merged